module.exports = {
  b: 'burn',
  e: 'description',
  d: 'distribution',
  dt: 'dataType',
  f: 'file',
  h: 'history',
  i: 'initialValue',
  l: 'lag',
  m: 'method',
  n: 'name',
  o: 'once',
  s: 'steps',
  sh: 'show',
  sm: 'samples',
  p: 'params',
  t: 'typeCode',
  u: 'useAsParameter',
  v: 'value',
  z: 'units'
}
